name: shope_taske
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  path: ^1.9.1
  path_provider: ^2.1.5
  sqflite: ^2.4.2


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.9
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/icon/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
    - family: Tajawal-bold
      fonts:
        - asset: assets/fonts/Tajawal-Bold.ttf
    - family: Tajawal-medium
      fonts:
        - asset: assets/fonts/Tajawal-Medium.ttf
